server:
  port: 8989
  jsp-servlet:
    init-parameters:
      development: true
  context-path: /ems_red
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/ems_gray
    url: jdbc:mysql://192.168.71.11:8066/test_schema
    username: root
    password: root
  http: #处理中文乱码
    encoding:
      charset: UTF-8
      force: true
mybatis:
  mapper-locations: classpath:com/baizhi/mappers/*.xml
  type-aliases-package: com.baizhi.entity